apiVersion: v1
kind: Secret
metadata:
  name: shardvault-secrets
  namespace: shardvault
type: Opaque
stringData:
  # Change this before production use!
  JWT_SECRET: "shard_secret_key_2024_distributed"
