###############################################################
# node-b.yaml
# Storage Node B — holds Shard 1 (middle third of every file)
# Scheduled on: Machine B (worker), label: laptop=laptop-b
###############################################################

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-b-pvc
  namespace: distributed-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-b
  namespace: distributed-storage
  labels:
    app: node-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-b
  template:
    metadata:
      labels:
        app: node-b
    spec:
      # 2-LAPTOP MODE: Node B runs on Machine B (the worker laptop)
      nodeSelector:
        laptop: "laptop-b"
      containers:
        - name: node-b
          image: REGISTRY_IP:5050/storage-node:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5003
          env:
            - name: NODE_NAME
              value: "Node_B"
            - name: PORT
              value: "5003"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: shard-secret
                  key: JWT_SECRET
          volumeMounts:
            - name: node-b-storage
              mountPath: /data/shards
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 5003
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 5003
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: node-b-storage
          persistentVolumeClaim:
            claimName: node-b-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: node-b
  namespace: distributed-storage
spec:
  selector:
    app: node-b
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
  type: ClusterIP
