###############################################################
# node-a.yaml
# Storage Node A — holds Shard 0 (first third of every file)
# Scheduled on: Machine A (master), label: laptop=laptop-a
###############################################################

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-a-pvc
  namespace: distributed-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-a
  namespace: distributed-storage
  labels:
    app: node-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-a
  template:
    metadata:
      labels:
        app: node-a
    spec:
      # Node A physically lives on Machine A (master)
      nodeSelector:
        laptop: "laptop-a"
      containers:
        - name: node-a
          image: REGISTRY_IP:5050/storage-node:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5002
          env:
            - name: NODE_NAME
              value: "Node_A"
            - name: PORT
              value: "5002"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: shard-secret
                  key: JWT_SECRET
          volumeMounts:
            - name: node-a-storage
              mountPath: /data/shards
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: node-a-storage
          persistentVolumeClaim:
            claimName: node-a-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: node-a
  namespace: distributed-storage
spec:
  selector:
    app: node-a
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP
