apiVersion: v1
kind: Secret
metadata:
  name: shard-secret
  namespace: distributed-storage
type: Opaque
stringData:
  # Plain text — K8s will base64-encode it automatically
  JWT_SECRET: "shard_secret_key_2024_distributed"
