apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
    - name: app
      image: ubuntu
      command: ["sh", "-c", "echo NODE_ID=$NODE_ID && sleep 3600"]
      env:
        - name: NODE_ID
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NODE_ID